tasks:
  - name: server
    init: npm install #3&& npm run build
    command: | 
     npm run dev
  - name: client
    init: cd $PWD/client && npm install

ports:
  - port: 3000
    visibility: public
    onOpen: ignore